### ISSUE TITLE
Support PHP 8.2

### ISSUE THREAD

**Issue by acelaya** [weierophinney/laminas-ci-swoole-builder#2]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Create release with PHP 8.2 artifacts.

*See https://github.com/mezzio/mezzio-swoole/issues/103*

**Comment by acelaya** [comment]
I could try to contribute this, but I'm not sure where to start from. I may need some guidance 😅

**Comment by acelaya** [comment]
Ok, I believe this should do the trick https://github.com/weierophinney/laminas-ci-swoole-builder/pull/3

**Comment by weierophinney** [comment]
Fixed with #3; will tag 0.2.1 shortly and build artifacts.

**Comment by acelaya** [comment]
Thanks!
